name: JukeboxTiki
main: work.torp.jukeboxtiki.Main
version: 1.0
api-version: 1.13
commands:
   givespawner:
      description: Runs the /givespawner command
      usage: /givespawner
      aliases: [gs]